// Each entry's macros are the amount for exactly `quantity` `unit` of that food —
// e.g. Almonds is 2g carbs / 2g protein / 12g fat per 10 pc, not per 100g.
// unit is one of: 'g' (grams), 'ml' (millilitres), 'pc' (piece/count),
// 'cup', 'tbsp', 'tsp', 'slice', 'scoop', 'bowl'.
export const foodDatabase = [
  { name: 'Almonds', quantity: 10, unit: 'pc', carbs: 2, protein: 2, fat: 12 },
  { name: 'Apple', quantity: 1, unit: 'pc', carbs: 25, protein: 0.5, fat: 0.3 },
  { name: 'Apple Cider Vinegar', quantity: 15, unit: 'ml', carbs: 0.1, protein: 0, fat: 0 },
  { name: 'Arjuna', quantity: 1, unit: 'pc', carbs: 0.25, protein: 3, fat: 0 },
  { name: 'Avli', quantity: 100, unit: 'g', carbs: 86.2, protein: 5.69, fat: 0.92 },
  { name: 'Baked Chicken', quantity: 100, unit: 'g', carbs: 3.1, protein: 18.3, fat: 2.7 },
  { name: 'Banana Rabotta', quantity: 1, unit: 'pc', carbs: 27, protein: 1.3, fat: 0.4 },
  { name: 'Basmati Rice', quantity: 1, unit: 'cup', carbs: 45, protein: 4.3, fat: 0.4 },
  { name: 'Beef', quantity: 100, unit: 'g', carbs: 0, protein: 20, fat: 30 },
  { name: 'Beetroot', quantity: 100, unit: 'g', carbs: 10, protein: 1.6, fat: 0.2 },
  { name: 'Biscuit Hide and Seek', quantity: 4, unit: 'pc', carbs: 8, protein: 1, fat: 4 },
  { name: 'Black Coffee with Jaggery', quantity: 1, unit: 'cup', carbs: 5.1, protein: 0.1, fat: 0 },
  { name: 'Black Raisins', quantity: 1, unit: 'tbsp', carbs: 7.5, protein: 0, fat: 0 },
  { name: 'Black Tea', quantity: 1, unit: 'cup', carbs: 0, protein: 0, fat: 0 },
  { name: 'Boost', quantity: 1, unit: 'cup', carbs: 49, protein: 0, fat: 0 },
  { name: 'Broccoli', quantity: 100, unit: 'g', carbs: 4.9, protein: 3, fat: 0.4 },
  { name: 'Broccoli Boiled', quantity: 100, unit: 'g', carbs: 4.4, protein: 3.7, fat: 0.4 },
  { name: 'Brown Rice', quantity: 100, unit: 'g', carbs: 23, protein: 2.3, fat: 0.8 },
  { name: 'Butter Milk', quantity: 200, unit: 'g', carbs: 12, protein: 2.1, fat: 12.1 },
  { name: 'Cabbage', quantity: 100, unit: 'g', carbs: 2.7, protein: 1.8, fat: 0.1 },
  { name: 'Capsicum (Small)', quantity: 1, unit: 'pc', carbs: 3.4, protein: 0.6, fat: 0.1 },
  { name: 'Carrot', quantity: 1, unit: 'pc', carbs: 6, protein: 0.6, fat: 0.1 },
  { name: 'Carrot Juice', quantity: 1, unit: 'cup', carbs: 22, protein: 0.5, fat: 0.2 },
  { name: 'Cashew', quantity: 28, unit: 'g', carbs: 9, protein: 5, fat: 12 },
  { name: 'Chapathi', quantity: 1, unit: 'pc', carbs: 20, protein: 3.8, fat: 2.3 },
  { name: 'Cheese', quantity: 1, unit: 'slice', carbs: 1, protein: 6, fat: 5 },
  { name: 'Chicken Biryani', quantity: 1, unit: 'bowl', carbs: 19, protein: 35, fat: 18.6 },
  { name: 'Chicken Breast', quantity: 100, unit: 'g', carbs: 0, protein: 31.5, fat: 3.6, calories: 165 },
  { name: 'Chicken Curry', quantity: 1, unit: 'cup', carbs: 8.5, protein: 5.1, fat: 6.5 },
  { name: 'Chicken Fry', quantity: 100, unit: 'g', carbs: 6.5, protein: 13.5, fat: 17.9 },
  { name: 'Chicken Tandoori', quantity: 150, unit: 'g', carbs: 3.2, protein: 30, fat: 7 },
  { name: 'Chips', quantity: 28, unit: 'g', carbs: 15, protein: 1.8, fat: 9.5 },
  { name: 'Chia Seed', quantity: 10, unit: 'g', carbs: 3.75, protein: 2.7, fat: 3.25 },
  { name: 'Coconut', quantity: 10, unit: 'g', carbs: 1.3, protein: 0.4, fat: 4.2 },
  { name: 'Coconut Curry', quantity: 1, unit: 'tbsp', carbs: 2.5, protein: 0.6, fat: 2.9 },
  { name: 'Coconut Milk', quantity: 100, unit: 'g', carbs: 2.0, protein: 0.3, fat: 33.49 },
  { name: 'Coffee', quantity: 1, unit: 'cup', carbs: 0, protein: 0, fat: 0 },
  { name: 'Coriander Powder', quantity: 1, unit: 'tsp', carbs: 5.4, protein: 0.7, fat: 7.4 },
  { name: 'Cumin Flour', quantity: 10, unit: 'g', carbs: 7.7, protein: 2.3, fat: 1 },
  { name: 'Cucumber', quantity: 100, unit: 'g', carbs: 1.7, protein: 0.7, fat: 0.1 },
  { name: 'Curd', quantity: 1, unit: 'cup', carbs: 5.3, protein: 3.9, fat: 3.7 },
  { name: 'Dates', quantity: 1, unit: 'pc', carbs: 9.7, protein: 2.8, fat: 0.3 },
  { name: 'Dosa', quantity: 1, unit: 'pc', carbs: 29, protein: 2, fat: 1 },
  { name: 'Egg Whole', quantity: 1, unit: 'pc', carbs: 0.6, protein: 6, fat: 5 },
  { name: 'Egg White', quantity: 1, unit: 'pc', carbs: 0.1, protein: 3, fat: 0 },
  { name: 'Fish Boiled', quantity: 100, unit: 'g', carbs: 0, protein: 20, fat: 1.8 },
  { name: 'Fish Fry', quantity: 100, unit: 'g', carbs: 0, protein: 25, fat: 11.02 },
  { name: 'Flaxseed', quantity: 1, unit: 'tbsp', carbs: 0, protein: 4, fat: 3 },
  { name: 'Fruit Juice', quantity: 1, unit: 'cup', carbs: 11.5, protein: 0.5, fat: 0 },
  { name: 'Ghee', quantity: 1, unit: 'tbsp', carbs: 0, protein: 0, fat: 9 },
  { name: 'Ginger Root', quantity: 10, unit: 'g', carbs: 1.8, protein: 0.18, fat: 0.2 },
  { name: 'Guava', quantity: 1, unit: 'pc', carbs: 8.5, protein: 4.2, fat: 0 },
  { name: 'Honey', quantity: 1, unit: 'tsp', carbs: 17, protein: 0, fat: 0 },
  { name: 'Ice Cream', quantity: 1, unit: 'scoop', carbs: 25, protein: 2.5, fat: 7 },
  { name: 'Jackfruit Raw', quantity: 100, unit: 'g', carbs: 39, protein: 1.1, fat: 0.4 },
  { name: 'Jam', quantity: 1, unit: 'tbsp', carbs: 13.4, protein: 0, fat: 0 },
  { name: 'Mango', quantity: 1, unit: 'pc', carbs: 27, protein: 0.6, fat: 0.6 },
  { name: 'Milk', quantity: 1, unit: 'cup', carbs: 12, protein: 8.3, fat: 4.7 },
  { name: 'Milk Biscuit', quantity: 1, unit: 'pc', carbs: 24, protein: 1.5, fat: 4.9 },
  { name: 'Mixed Pulav', quantity: 1, unit: 'bowl', carbs: 28, protein: 9.7, fat: 10.8 },
  { name: 'Paneer', quantity: 100, unit: 'g', carbs: 1.5, protein: 18, fat: 20 },
  { name: 'Rice', quantity: 1, unit: 'cup', carbs: 39, protein: 1.5, fat: 0.8 },
  { name: 'Roti', quantity: 1, unit: 'pc', carbs: 15, protein: 2.5, fat: 1.5 },
];
